#!/bin/bash

docker \
    --context default \
    run \
        --interactive \
        --rm \
        --tty \
        --volume "${HOME}/.config/stripe:/root/.config/stripe" \
        --volume "${PWD}:/stripe" \
        --workdir /stripe \
    stripe/stripe-cli
	"$@"
