#!/bin/bash

docker \
  --context default
  run \
    --env "BW_SESSION=${BW_SESSION}" \
    --interactive \
    --rm \
    --tty \
    --volume "${HOME}/.config/Bitwarden CLI:/root/.config/Bitwarden CLI" \
    --volume "$(pwd):/bw" \
	bitwarden-cli \
	"$@"
