#!/bin/bash

docker \
    --context default \
    run \
        --interactive \
        --rm \
        --tty \
        --volume "${HOME}/.aws:/root/.aws" \
        --volume "${PWD}:/ecs-cli" \
    ecs-cli \
    "$@"
